package dev.trindadedev.tooltelegram.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

public val LightColorScheme: ColorScheme =
    ColorScheme(
        primary = Color(0xFF41682C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFC1F0A3),
        onPrimaryContainer = Color(0xFF052100),
        inversePrimary = Color(0xFFA6D48A),
        secondary = Color(0xFF55624C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD9E7CB),
        onSecondaryContainer = Color(0xFF131F0D),
        tertiary = Color(0xFF196969),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFA8EFEF),
        onTertiaryContainer = Color(0xFF002021),
        background = Color(0xFFF5FBEF),
        onBackground = Color(0xFF181D14),
        surface = Color(0xFFF5FBEF),
        onSurface = Color(0xFF181D14),
        surfaceVariant = Color(0xFFE0E4D7),
        onSurfaceVariant = Color(0xFF43493E),
        surfaceTint = Color(0xFF41682C),
        inverseSurface = Color(0xFF2D3228),
        inverseOnSurface = Color(0xFFEEF3E4),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF72786C),
        outlineVariant = Color(0xFFC4C8BB),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF5FBEF),
        surfaceDim = Color(0xFFD6DCD0),
        surfaceContainer = Color(0xFFEAF0E4),
        surfaceContainerHigh = Color(0xFFE4EADE),
        surfaceContainerHighest = Color(0xFFE0E4D7),
        surfaceContainerLow = Color(0xFFF0F5EA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
    )

public val DarkColorScheme: ColorScheme =
    ColorScheme(
        primary = Color(0xFFA6D48A),
        onPrimary = Color(0xFF143801),
        primaryContainer = Color(0xFF2A5016),
        onPrimaryContainer = Color(0xFFC1F0A3),
        inversePrimary = Color(0xFF41682C),
        secondary = Color(0xFFBDCBB0),
        onSecondary = Color(0xFF283420),
        secondaryContainer = Color(0xFF3E4A35),
        onSecondaryContainer = Color(0xFFD9E7CB),
        tertiary = Color(0xFF8CD3D2),
        onTertiary = Color(0xFF003737),
        tertiaryContainer = Color(0xFF004F50),
        onTertiaryContainer = Color(0xFFA8EFEF),
        background = Color(0xFF101509),
        onBackground = Color(0xFFE0E4D7),
        surface = Color(0xFF101509),
        onSurface = Color(0xFFE0E4D7),
        surfaceVariant = Color(0xFF43493E),
        onSurfaceVariant = Color(0xFFC4C8BB),
        surfaceTint = Color(0xFFA6D48A),
        inverseSurface = Color(0xFFE0E4D7),
        inverseOnSurface = Color(0xFF2D3228),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFF8D9386),
        outlineVariant = Color(0xFF43493E),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF363B31),
        surfaceDim = Color(0xFF101509),
        surfaceContainer = Color(0xFF1D2118),
        surfaceContainerHigh = Color(0xFF272B23),
        surfaceContainerHighest = Color(0xFF32362D),
        surfaceContainerLow = Color(0xFF181D14),
        surfaceContainerLowest = Color(0xFF0A1002),
    )
